// components/JapaneseTime.vue
<script setup lang="ts">
type JapaneseTimeAttributes = {
	year?: string|number,
	month?: string|number,
	day?: string|number,
}

const props = defineProps<JapaneseTimeAttributes>();

const dateTimeValue = toRef("");
const displayValue = toRef("");
const usingTimeElement = toRef(true);
if (props.year != undefined) {
	if (props.month != undefined) {
		if (props.day != undefined) {
			displayValue.value = `${props.year}年${props.month}月${props.day}日`
			dateTimeValue.value = `${props.year}-${props.month}-${props.day}`;
		} else {
			displayValue.value = `${props.year}年${props.month}月`
			dateTimeValue.value = `${props.year}-${props.month}`;
		}
	} else {
		displayValue.value = `${props.year}年`
		dateTimeValue.value = `${props.year}`
	}
} else if (props.month != undefined) {
	if (props.day != undefined) {
		displayValue.value = `${props.month}月${props.day}日`
		dateTimeValue.value = `${props.month}-${props.day}`;
	} else {
		displayValue.value = `${props.month}月`;
		usingTimeElement.value = false;
	}
} else if (props.day != undefined) {
	displayValue.value = `${props.day}日${props.day}`;
	usingTimeElement.value = false;
} else {
	usingTimeElement.value = false;
}
</script>

<template>
	<time v-if="usingTimeElement" :datetime="dateTimeValue" v-text="displayValue"></time>
	<span v-else v-text="displayValue"></span>
</template>

<style scoped>

</style>

// components/JapaneseTime.tsx
export default function JapaneseTime({year, month, day}: { year?: number | string, month?: number | string, day?: number | string }) {
  let dateTimeValue = "";
  let displayValue = "";
  let usingTimeElement = true;
  if (year != undefined) {
    if (month != undefined) {
      if (day != undefined) {
        displayValue = `${year}年${month}月${day}日`
        dateTimeValue = `${year}-${month}-${day}`;
      } else {
        displayValue = `${year}年${month}月`
        dateTimeValue = `${year}-${month}`;
      }
    } else {
      displayValue = `${year}年`
      dateTimeValue = `${year}`
    }
  } else if (month != undefined) {
    if (day != undefined) {
      displayValue = `${month}月${day}日`
      dateTimeValue = `${month}-${day}`;
    } else {
      displayValue = `${month}月`;
      usingTimeElement = false;
    }
  } else if (day != undefined) {
    displayValue = `${day}日${day}`;
    usingTimeElement = false;
  } else {
    usingTimeElement = false;
  }
  if (usingTimeElement) {
    return (
      <time dateTime={dateTimeValue}>
        {displayValue}
      </time>
    )
  } else {
    return (
      <span>{displayValue}</span>
    )
  }
}
