// components/MemberCard.vue
<script setup lang="ts">
import UpperBodyImage from "~/components/UpperBodyImage.vue";

type MemberCardAttributes = {
	name: string,
	yomi: string,
	profileId: string,
	imageId: string,
	imageAlt: string,
}

const props = defineProps<MemberCardAttributes>();
</script>

<template>
	<section class="tw-items-center">
		<UpperBodyImage :memberId="props.imageId" :alt="props.imageAlt" :isDisableMarginTopExpand="true" />
			<div class="tw-mb-28 tw-leading-loose tw-text-black">
				<p class="font-slogan tw-text-center tw-text-3xl xl:tw-text-5xl" v-text="props.name"></p>
				<p class="font-slogan tw-text-center tw-mb-14" v-text="props.yomi"></p>
				<div class="tw-flex tw-flex-col">
					<NuxtLink class="tw-self-stretch tw-rounded-full tw-bg-rose-500 hover:tw-bg-rose-700 tw-text-white tw-px-8 tw-py-4 tw-text-center" :href="`/talents/${props.profileId}`" rel="noopener noreferrer">
						紹介ページへ
					</NuxtLink>
				</div>
			</div>
	</section>
</template>

<style scoped>

</style>

// components/MemberCard.tsx
import Link from "next/link";
import UpperBodyImage from "@/components/UpperBodyImage";

type MemberCardAttributes = {
  name: string,
  yomi: string,
  profileId: string,
  imageId: string,
  imageAlt: string,
}

export default function MemberCard({name, yomi, profileId, imageId, imageAlt}: MemberCardAttributes) {
  return (
    <section className="items-center">
      <UpperBodyImage memberId={imageId} alt={imageAlt} isDisableMarginTopExpand={true}/>
      <div className="mb-28 leading-loose text-black">
        <p className="font-slogan text-center text-3xl xl:text-5xl">{name}</p>
        <p className="font-slogan text-center mb-14">{yomi}</p>
        <div className="flex flex-col">
          <Link className="self-stretch rounded-full bg-rose-500 hover:bg-rose-700 text-white px-8 py-4 text-center" href={`/talents/${profileId}`} rel="noopener noreferrer">
            紹介ページへ
          </Link>
        </div>
      </div>
    </section>
  )
}
