// components/ProfileHead.vue
<script setup lang="ts">
type ProfileHeadAttributes = {
	name: string,
	yomi: string,
	catchphrase: string,
	isDisableCatchphraseBrackets?: boolean,
}
const props = defineProps<ProfileHeadAttributes>();
</script>

<template>
	<div class="tw-mb-28 tw-leading-loose">
		<p class="font-slogan tw-text-center tw-text-3xl xl:tw-text-5xl">{{ props.name }}</p>
		<p class="font-slogan tw-text-center tw-mb-14">{{ props.yomi }}</p>
		<p v-if="!(props.isDisableCatchphraseBrackets ?? false)" class="font-slogan tw-text-center tw-mb-14 tw-text-xl xl:tw-text-3xl">「{{ props.catchphrase }}」</p>
		<p v-else class="font-slogan tw-text-center tw-mb-14 tw-text-xl xl:tw-text-3xl">{{ props.catchphrase }}</p>
		<p class="tw-mb-14">
			<slot />
		</p>
	</div>
</template>

// components/ProfileHead.tsx
type ProfileHeadAttributes = {
  name: string,
  yomi: string,
  catchphrase: string,
  isDisableCatchphraseBrackets?: boolean,
  children: React.ReactNode
}

export default function ProfileHead({name, yomi, catchphrase, isDisableCatchphraseBrackets, children}: ProfileHeadAttributes) {
  return (
    <div className="mb-28 leading-loose">
      <p className="font-slogan text-center text-3xl xl:text-5xl">{name}</p>
      <p className="font-slogan text-center mb-14">{yomi}</p>
      <p className="font-slogan text-center mb-14 text-xl xl:text-3xl">{`${(isDisableCatchphraseBrackets ?? false) ? "" : "「"}${catchphrase}${(isDisableCatchphraseBrackets ?? false) ? "" : "」"}`}</p>
      <p className="mb-14">{children}</p>
    </div>
  );
}
