// components/SectionHeader.tsx
type SectionHeaderAttributes = {
  isDark?: boolean;
  title: string | React.ReactNode,
  description: string | React.ReactNode,
  titleClass?: string,
  descriptionClass?: string
  titleColor?: string,
  descriptionColor?: string,
}

export default function SectionHeader({title, description, titleClass, descriptionClass, isDark, titleColor, descriptionColor}: SectionHeaderAttributes) {
  return (
    <div className="mb-14 text-center" data-aos="fade-down" data-aos-duration="2000">
      <div className={titleClass ?? `font-bold text-3xl${(titleColor !== undefined) ? ` text-${titleColor}` : ""}`}>{title}</div>
      <div className={descriptionClass ?? `text-sm ${((descriptionColor !== undefined) ? `text-${descriptionColor}` : (isDark ?? false) ? "text-rose-300" : "text-rose-600")}`}>{description}</div>
    </div>
  )
}

// components/SectionHeader.vue
<script setup lang="ts">
type SectionHeaderAttributes = {
	isDark?: boolean;
	title: string,
	description: string,
	titleClass?: string,
	descriptionClass?: string
	titleColor?: string,
	descriptionColor?: string,
}

const props = defineProps<SectionHeaderAttributes>();
</script>

<template>
	<div class="tw-mb-14 tw-text-center" data-aos="fade-down" data-aos-duration="2000">
		<div :class="titleClass ?? `tw-font-bold tw-text-3xl${(titleColor !== undefined) ? ` tw-text-${titleColor}` : ''}`" v-text="title"></div>
		<div :class="descriptionClass ?? `tw-text-sm ${((descriptionColor !== undefined) ? `tw-text-${descriptionColor}` : (isDark ?? false) ? 'tw-text-rose-300' : 'tw-text-rose-600')}`" v-text="description"></div>
	</div>
</template>
