// components/YouTubeChannel.tsx
export default function YouTubeChannel({channelId, handle, customLink, userId}: { channelId?: string, handle?: string, customLink?: string, userId?: string }) {
  if (channelId !== undefined) {
    return (
      <a className="self-stretch flex shrink items-center rounded-full bg-rose-500 hover:bg-rose-700 text-white px-8 py-4" href={`https://www.youtube.com/channel/${channelId}`} target="_blank" rel="noopener noreferrer">
        YouTube
      </a>
    );
  } else if (handle !== undefined) {
    return (
      <a className="self-stretch flex shrink items-center rounded-full bg-rose-500 hover:bg-rose-700 text-white px-8 py-4" href={`https://www.youtube.com/@${handle}`} target="_blank" rel="noopener noreferrer">
        YouTube
      </a>
    );
  } else if (customLink !== undefined) {
    return (
      <a className="self-stretch flex shrink items-center rounded-full bg-rose-500 hover:bg-rose-700 text-white px-8 py-4" href={`https://www.youtube.com/c/${customLink}`} target="_blank" rel="noopener noreferrer">
        YouTube
      </a>
    );
  } else if (userId !== undefined) {
    return (
      <a className="self-stretch flex shrink items-center rounded-full bg-rose-500 hover:bg-rose-700 text-white px-8 py-4" href={`https://www.youtube.com/user/${userId}`} target="_blank" rel="noopener noreferrer">
        YouTube
      </a>
    );
  } else {
    return (
      <a className="self-stretch flex shrink items-center rounded-full bg-rose-500 hover:bg-rose-700 text-white px-8 py-4">
        YouTube (リンク切れ)
      </a>
    );
  }
}

// components/YouTubeChannel.vue
<script setup lang="ts">
import ButtonLinkBase from "~/components/ButtonLinkBase.vue";

type YouTubeChannelAttributes = ({
	/**
	 * チャンネルの一意のIDです。おおよそ`UC****`のようなIDです。
	 */
	channelId?: string,
	/**
	 * `@`から始まる認識しやすいIDです。
	 */
	handle?: string,
	/**
	 * ハンドル化以前にカスタムリンクを設定したユーザーの`/c/`以降です
	 */
	customLink?: string,
	/**
	 * 従来のユーザーIDです。`/user/`以降のことを指します。
	 */
	userId?: string
});

const props = defineProps<YouTubeChannelAttributes>();

const href = computed({
	get: () => {
		if (props.channelId != undefined) {
			return `https://www.youtube.com/channel/${props.channelId}`;
		} else if (props.customLink != undefined) {
			return `https://www.youtube.com/c/${props.customLink}`;
		} else if (props.userId != undefined) {
			return `https://www.youtube.com/user/${props.userId}`;
		} else if (props.handle != undefined) {
			return `https://www.youtube.com/@${props.handle}`;
		} else {
			return ""
		}
	}
})
const target = computed({
	get: () => {
		if (props.channelId != undefined || props.customLink != undefined || props.userId != undefined || props.handle != undefined) {
			return "_blank";
		} else {
			return ""
		}
	}
})
const rel = computed({
	get: () => {
		if (props.channelId != undefined || props.customLink != undefined || props.userId != undefined || props.handle != undefined) {
			return "noopener noreferrer";
		} else {
			return ""
		}
	}
})
const text = computed({
	get: () => {
		if (props.channelId != undefined || props.customLink != undefined || props.userId != undefined || props.handle != undefined) {
			return "YouTube";
		} else {
			return "YouTube (リンク切れ)"
		}
	}
})
</script>

<template>
	<ButtonLinkBase :href="href" :target="target" :rel="rel">
		{{ text }}
	</ButtonLinkBase>
</template>
