// app/talents/kohinata_gaku/page.tsx
"use client";
import {useEffect} from "react";
import '../../fonts.css';
import AOS from 'aos';
import 'aos/dist/aos.css';
import 'swiper/css';
import 'swiper/css/a11y';
import 'swiper/css/autoplay';
import MemberTemplate from "@/components/MemberTemplate";
import FullBodyImage from "@/components/FullBodyImage";
import ProfileHead from "@/components/ProfileHead";
import XProfile from "@/components/XProfile";
import YouTubeChannel from "@/components/YouTubeChannel";

export default function Page() {
  useEffect(() => {
    AOS.init();
  }, [])
  return (
    <MemberTemplate>
      <aside className="self-start text-center w-full xl:w-auto">
        <FullBodyImage memberId="kohinata_gaku" alt="Kohinata Gaku"/>
      </aside>
      <section className="px-10 xl:px-14 py-14 text-base">
        <section>
          <ProfileHead name="小日向がく" yomi="Kohinata Gaku" catchphrase="はっきんぐ？なにそれおいし～の？">
          CEH，OSCP，OSEP等のハッキング能力を証明する資格を取得しているハッカー系Vtuber💻💀<br/>
          Youtubeにてハッカー（攻撃者）がどのようにしてあなたの情報を日々狙っているのかを解説している<br/>
          映画のような遠い世界の話のように感じるハッキング行為だが、気づかないうちに意外と身近に危険は潜んでいる<br/>
          日頃からの情報セキュリティの備え方について一緒に学んでいこう！✨
         </ProfileHead>
          <div className="w-fit flex flex-col xl:flex-row xl:flex-wrap justify-between items-center gap-4">
            <XProfile userId="427Kohi"/>
            <YouTubeChannel handle="逸般人のがくHackerGaku"/>
          </div>
        </section>
      </section>
    </MemberTemplate>
  );
}

// pages/talents/kohinata_gaku/index.vue
<script setup lang="ts">
definePageMeta({
	layout: 'member-page'
})
const name = "小日向がく";
const yomi = "Kohinata Gaku";
const description = "はっきんぐ？なにそれおいし～の？";
useSeoMeta({
	title: name,
	description,
	ogType: "profile",
	ogTitle: name,
	ogDescription: description,
	profileUsername: name
})
</script>

<template>
	<aside class="tw-self-start tw-text-center tw-w-full xl:tw-w-auto">
		<FullBodyImage
			memberId="kohinata_gaku"
			:alt="yomi"
		/>
	</aside>
	<section class="tw-px-10 xl:tw-px-14 tw-py-14 tw-text-base">
		<section>
			<ProfileHead :name="name" :yomi="yomi" :catchphrase="description">
				CEH，OSCP，OSEP等のハッキング能力を証明する資格を取得しているハッカー系Vtuber💻💀<br/>
				Youtubeにてハッカー（攻撃者）がどのようにしてあなたの情報を日々狙っているのかを解説している<br/>
				映画のような遠い世界の話のように感じるハッキング行為だが、気づかないうちに意外と身近に危険は潜んでいる<br/>
				日頃からの情報セキュリティの備え方について一緒に学んでいこう！✨
			</ProfileHead>
			<div class="tw-w-fit tw-flex tw-flex-col xl:tw-flex-row xl:tw-flex-wrap tw-justify-between tw-items-center tw-gap-4">
				<XProfile userId="427Kohi"/>
				<YouTubeChannel handle="逸般人のがくHackerGaku"/>
			</div>
		</section>
	</section>
</template>
